version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: docker/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8091:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: docker/app.docker
        volumes:
            - ./:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
#        command: sh start.sh
    database:
        image: mysql:5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=kwntu"
        ports:
            - "33061:3306"
